export const CARDS = [
  {
    image: "./imgs/card__imgs/amur.webp",
    author: "Марсель Руссо",
    title: "Охота на амура",
    material: "Холст, Масло (50х80)",
    price: 14500,
    country: "france",
  },
  {
    image: "./imgs/card__imgs/lady-dog.webp",
    author: "Анри Селин",
    title: "Дама с собачкой",
    material: "Акрил, бумага (50х80)",
    price: 16500,
    country: "france",
  },
  {
    image: "./imgs/card__imgs/procedure.webp",
    author: "Франсуа Дюпон",
    title: "Процедура",
    material: "Цветная литография (40х60)",
    price: 20000,
    country: "france",
  },
  {
    image: "./imgs/card__imgs/rose.webp",
    author: "Луи Детуш",
    title: "Роза",
    material: "Бумага, акрил (50х80)",
    price: 12000,
    country: "france",
  },
  {
    image: "./imgs/card__imgs/bird-harvesting.webp",
    author: "Франсуа Дюпон",
    title: "Птичья трапеза",
    material: "Цветная литография (50х80)",
    price: 22500,
    country: "france",
  },
  {
    image: "./imgs/card__imgs/fish-picture.webp",
    author: "Пьер Моранж",
    title: "Пейзаж с рыбой",
    material: "Цветная литография (50х80)",
    price: 20000,
    country: "france",
  },
  {
    image: "./imgs/card__imgs/germany/aboveCity.png",
    author: "Курт Вернер",
    title: "Над городом",
    material: "Цветная литография (40х60)",
    price: 16000,
    country: "germany",
  },
  {
    image: "./imgs/card__imgs/germany/littleBirds.png",
    author: "Макс Рихтер",
    title: "Птенцы",
    material: "Холст, масло(50х80)",
    price: 14500,
    country: "germany",
  },
  {
    image: "./imgs/card__imgs/germany/aroundTrees.png",
    author: "Мартин Майер",
    title: "Среди листьев",
    material: "Цветная литография (40х60)",
    price: 20000,
    country: "germany",
  },
  {
    image: "./imgs/card__imgs/germany/shinyBird.png",
    author: "Герман Беккер",
    title: "Яркая птица",
    material: "Цветная литография (40х60)",
    price: 13000,
    country: "germany",
  },
  {
    image: "./imgs/card__imgs/germany/woodpeckers.png",
    author: "Вульф Бауэр",
    title: "Дятлы",
    material: "Бумага, Акрил (50х80)",
    price: 20000,
    country: "germany",
  },
  {
    image: "./imgs/card__imgs/germany/bigWaters.png",
    author: "Вальтер Хартманн",
    title: "Большие воды",
    material: "Бумага, акрил (50х80)",
    price: 23000,
    country: "germany",
  },
  {
    image: "./imgs/card__imgs/england/wildAnimal.png",
    author: "Пол Смит",
    title: "Дикий зверь",
    material: "Акварель, бумага (50х80)",
    price: 19500,
    country: "england",
  },
  {
    image: "./imgs/card__imgs/england/mountains.png",
    author: "Джон Уайт",
    title: "Скалистый берег",
    material: "Цветная литография (40х60)",
    price: 17500,
    country: "england",
  },
  {
    image: "./imgs/card__imgs/england/riverAndCliffs.png",
    author: "Джим Уотсон",
    title: "Река и Горы",
    material: "Акварель, бумага(50х80)",
    price: 20500,
    country: "england",
  },
  {
    image: "./imgs/card__imgs/england/nightFish.png",
    author: "Эрик Гиллман",
    title: "Ночная рыба",
    material: "Бумага, акрил (50х80)",
    price: 12500,
    country: "england",
  },
  {
    image: "./imgs/card__imgs/england/whiteParrot.png",
    author: "Юджин Зилион",
    title: "Белый попугай",
    material: "Цветная литография (40x60)",
    price: 15500,
    country: "england",
  },
  {
    image: "./imgs/card__imgs/england/gingerCat.png",
    author: "Альфред Барр",
    title: "Рыжий кот",
    material: "Цветная литография (40х60)",
    price: 21000,
    country: "england",
  },
];
